name: Download Artifact

description: Download file to local or artifact to quickly share files between jobs

inputs:
  name:
    description: "Artifact name"
    default: "artifact"
  path:
    description: "Destination path"
    required: true
  force-use-github:
    description: "force download from github"
    default: false
    required: false

runs:
  using: composite
  steps:
    - name: Download artifact from github
      uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
      if: ${{ inputs.force-use-github == 'true' || runner.environment == 'github-hosted' }}
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
#    - name: Download artifact from local
#      uses: lynx-infra/download-artifact
#      if: ${{ input.force-use-github != 'true' && runner.environment == 'self-hosted' }}
#      with:
#        name: ${{ inputs.name }}
#        path: ${{ inputs.path }}
