name: Pnpm

description: Set up pnpm and install dependencies (including yarn fixture installs)

inputs:
  node-version:
    description: "Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0."
    default: "20"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3

    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: ${{ inputs['node-version'] }}
        cache: pnpm

    - name: Enable corepack
      if: ${{ inputs.node-version != '16' }}
      shell: bash
      run: |
        if [[ "${{runner.os}}" == "Windows" ]]; then
          # add the npm prefix to PATH to ensure the installed corepack work properly
          NPM_PREFIX=$(cygpath -u "$(npm config get prefix)")
          export PATH="$NPM_PREFIX:$PATH"
        fi
        npm install -g corepack@0.31.0 --force
        echo "Corepack version: $(corepack --version)"
        corepack enable

    - name: yarn
      shell: bash
      run: |
        cd fixtures/pnp
        yarn install
        cd ../pnp-global-cache-enabled
        yarn install

    - name: pnpm
      shell: bash
      run: |
        pnpm install
