name: Pnpm

description: Install pnpm

inputs:
  node-version:
    description: "Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0."
    default: "20"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ inputs['node-version'] }}
        cache: pnpm

    - name: Enable corepack
      if: ${{ inputs.node-version != '16' }}
      shell: bash
      run: |
        if [[ "${{runner.os}}" == "Windows" ]]; then
          # add the npm prefix to PATH to ensure the installed corepack work properly
          NPM_PREFIX=$(cygpath -u "$(npm config get prefix)")
          export PATH="$NPM_PREFIX:$PATH"
        fi
        npm install -g corepack@0.31.0 --force
        echo "Corepack version: $(corepack --version)"
        corepack enable

    - name: yarn
      shell: bash
      run: |
        cd fixtures/pnp
        yarn install

    - name: pnpm
      shell: bash
      run: |
        pnpm install
