name: Benchmark

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "**/*.md"
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Setup benchmark data
        run: cd benches && pnpm install --ignore-workspace

      - uses: Boshen/setup-rust@d6c3ed678c68bc13d6fc5c0df3c60970f4077428 # main
        with:
          cache-key: benchmark
          save-cache: ${{ github.ref_name == 'main' }}
          tools: cargo-codspeed

      - uses: ./.github/actions/pnpm
      - name: Build Benchmark
        env:
          RUSTFLAGS: "-C debuginfo=1 -C strip=none -g"
        run: cargo codspeed build

      - name: Run CPU benchmark
        uses: CodSpeedHQ/action@281164b0f014a4e7badd2c02cecad9b595b70537 # https://github.com/CodSpeedHQ/action/releases/tag/v4.10.6
        timeout-minutes: 30
        with:
          mode: simulation
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}

      - name: Run memory benchmark
        uses: CodSpeedHQ/action@281164b0f014a4e7badd2c02cecad9b595b70537 # https://github.com/CodSpeedHQ/action/releases/tag/v4.10.6
        timeout-minutes: 30
        with:
          mode: memory
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
