name: CI

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "**/*.md"
      - "!.github/workflows/ci.yml"
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "!.github/workflows/ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

defaults:
  run:
    shell: bash

jobs:
  cache: # Warm cache factory for all other CI jobs
    name: Check and Build
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
          - os: ubuntu-latest
          - os: macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: taiki-e/checkout-action@83ed61bfbe2b8abbb3c66e8b65b1335484c70009 # v1.4.1
      - uses: ./.github/actions/pnpm
      - uses: Boshen/setup-rust@d6c3ed678c68bc13d6fc5c0df3c60970f4077428 # main
        with:
          save-cache: ${{ github.ref_name == 'main' }}
          cache-key: warm

      - run: cargo check --all-features --locked

      - name: Publish Dry-run Check
        run: cargo publish --dry-run

      # Only need to build the test to create a warm cache on the main branch
      - name: Build cache by Cargo Check and Cargo Test
        if: ${{ github.ref_name == 'main' }}
        run: cargo test --all-features --no-run
        env:
          RUST_MIN_STACK: 8388608

  wasm:
    name: Check Wasm
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@83ed61bfbe2b8abbb3c66e8b65b1335484c70009 # v1.4.1

      - uses: Boshen/setup-rust@d6c3ed678c68bc13d6fc5c0df3c60970f4077428 # main
        with:
          cache-key: wasm
          save-cache: ${{ github.ref_name == 'main' }}

      - name: Check
        run: |
          rustup target add wasm32-unknown-unknown
          cargo check --all-features --target wasm32-unknown-unknown

  wasi:
    name: Test wasi target
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@83ed61bfbe2b8abbb3c66e8b65b1335484c70009 # v1.4.1

      - uses: Boshen/setup-rust@d6c3ed678c68bc13d6fc5c0df3c60970f4077428 # main
        with:
          cache-key: wasi
          save-cache: ${{ github.ref_name == 'main' }}

      - uses: ./.github/actions/pnpm

      - name: Build
        run: |
          rustup target add wasm32-wasip1-threads
          pnpm build --target wasm32-wasip1-threads

      - name: Test
        run: pnpm test
        env:
          WASI_TEST: 1

  typos:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@83ed61bfbe2b8abbb3c66e8b65b1335484c70009 # v1.4.1

      - uses: crate-ci/typos@631208b7aac2daa8b707f55e7331f9112b0e062d # v1.44.0
        with:
          files: .

  deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@83ed61bfbe2b8abbb3c66e8b65b1335484c70009 # v1.4.1

      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            src:
              - 'Cargo.lock'

      - uses: Boshen/setup-rust@d6c3ed678c68bc13d6fc5c0df3c60970f4077428 # main
        with:
          restore-cache: false
          tools: cargo-deny

      - if: steps.filter.outputs.src == 'true'
        run: cargo deny check

  unused-deps:
    name: Check Unused Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@83ed61bfbe2b8abbb3c66e8b65b1335484c70009 # v1.4.1
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            src:
              - '**/*.rs'
              - '**/Cargo.toml'
              - 'Cargo.lock'
      - uses: Boshen/setup-rust@d6c3ed678c68bc13d6fc5c0df3c60970f4077428 # main
        with:
          restore-cache: false
        if: steps.filter.outputs.src == 'true'
      - uses: cargo-bins/cargo-binstall@0b24824336e2b3800b0f89d9e08b2c08bfa3dcdd # main
        if: steps.filter.outputs.src == 'true'
      - run: cargo binstall --no-confirm cargo-shear@1
        if: steps.filter.outputs.src == 'true'
      - run: cargo shear
        if: steps.filter.outputs.src == 'true'

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@83ed61bfbe2b8abbb3c66e8b65b1335484c70009 # v1.4.1
      - name: Pnpm Setup
        uses: ./.github/actions/pnpm
      - uses: Boshen/setup-rust@d6c3ed678c68bc13d6fc5c0df3c60970f4077428 # main
        with:
          components: rustfmt
          restore-cache: false
      - run: cargo fmt --all -- --check
      - run: pnpm run prettier:ci
      - run: pnpm exec taplo format --check

  lint:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@83ed61bfbe2b8abbb3c66e8b65b1335484c70009 # v1.4.1
      - uses: Boshen/setup-rust@d6c3ed678c68bc13d6fc5c0df3c60970f4077428 # main
        with:
          components: clippy
      - run: cargo clippy --all-features -- -D warnings

  doc:
    name: Doc
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@83ed61bfbe2b8abbb3c66e8b65b1335484c70009 # v1.4.1
      - uses: Boshen/setup-rust@d6c3ed678c68bc13d6fc5c0df3c60970f4077428 # main
        with:
          components: rust-docs
      - run: RUSTDOCFLAGS='-D warnings --cfg docsrs' cargo doc --no-deps --all-features

  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-14
        node:
          - 20
          - 22
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: taiki-e/checkout-action@83ed61bfbe2b8abbb3c66e8b65b1335484c70009 # v1.4.1
      - uses: ./.github/actions/pnpm
        with:
          node-version: ${{ matrix.node }}
      - uses: Boshen/setup-rust@d6c3ed678c68bc13d6fc5c0df3c60970f4077428 # main
        with:
          cache-key: warm
      - run: cargo test --doc
      - run: cargo test --all-features
        env:
          RUST_MIN_STACK: 8388608
      - name: Build Node Bindings
        run: npm run build:binding:debug
      - name: Test
        run: npm test
      - name: Git status check
        run: |
          npm run format
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Working tree is dirty after tests/build. Please commit or revert the following changes:"
            git status --short
            exit 1
          fi
